### ISSUE TITLE
Code blocks that come first in an ordered list have little top padding

### ISSUE THREAD

**Issue by jrhoun** [liferay/liferay-learn#100]
**Describe the bug**
When a code block is used in a numbered list, there is very little padding between the numbered item and the code block that immediately follows.

**To Reproduce**

See: https://learn.liferay.com/commerce-2.x/installation-and-upgrades/installation-guide/using-the-liferay-commerce-docker-image.html

![image](https://user-images.githubusercontent.com/597214/72637180-8ebbf300-3915-11ea-9e46-2a17991a6e1f.png)

**Expected behavior**

Consistent top and bottom padding for code blocks.

![image](https://user-images.githubusercontent.com/597214/72637210-a1cec300-3915-11ea-8bf4-1624d5e77ce0.png)

**Additional context**
This might not be a bug really, but a oversight on my part. So it could be categorized as an enhancement - I think having some padding in a numbered list between the numbered item and the code block that immediately follows might help w/ readability.

**Comment by rdai10** [comment]
https://github.com/jrhoun/liferay-learn/pull/147
