### ISSUE TITLE
Search product toggle incorrectly wraps on wide screens

### ISSUE THREAD

**Issue by jpince** [liferay/liferay-learn#107]
**Describe the bug**
Search product toggle button wraps to a new line when screen is too wide. 

**To Reproduce**
1. Use a wide monitor or Chrome dev tools in responsive mode
1. Increase the width of the screen to 2751 or greater

**Result: caret wraps onto a new line**
![image](https://user-images.githubusercontent.com/14880618/75179928-fa9d3280-56ef-11ea-87a6-36f06f862d50.png)
If you expand it further, "Cloud" wraps onto an additional new line.

**Expected behavior**
Search product toggle button remains as one line.

**Comment by rdai10** [comment]
This issue will be fixed when DXP Docs goes public.

**Comment by jrhoun** [comment]
Seems fixed @jpince 
![2020-03-06_14-06-11](https://user-images.githubusercontent.com/597214/76126370-c2c9a100-5fb3-11ea-897c-05c330701cdc.gif)
