### ISSUE TITLE
Improvements for mobile

### ISSUE THREAD

**Issue by jpince** [liferay/liferay-learn#108]
**Suggested improvements for mobile site**
1. Increase button size on landing page
1. Hamburger menu at the top for links to other sites (Liferay.com, Training, etc.)
1. Increase text size (everywhere)
1. Left menu is collapsible
1. Right navigation/table of contents not necessary
1. When in a document, the product documentation selector doesn't work properly. After selecting the product, nothing happens. I have to touch the selector again for the page to navigate to the selected product.

Tested on Android Moto Z Play.

**Comment by jrhoun** [comment]
Fixed by https://issues.liferay.com/browse/LRDOCS-8203.
