### ISSUE TITLE
Line Spacing in numbered-bulleted list is different than in Github 

### ISSUE THREAD

**Issue by andrewwilkinsonLR** [liferay/liferay-learn#12]
**Describe the bug**
Line Spacing in numbered-bulleted list is different than in Github.

(See the screenshot below: "no space" and "space" are different in 4 locations, as indicated.)

![image](https://user-images.githubusercontent.com/51930500/68906716-1741cb80-06fa-11ea-9aab-dcf6d723dfbd.png)

Github: https://github.com/jrhoun/liferay-learn/blob/master/docs/commerce/2.x/en/installation-and-upgrades/installation-guide/deploying-liferay-commerce-to-an-existing-liferay-installation.md

Site: https://s3.wasabisys.com/learn.liferay.com/commerce-2.x/html/docs/installation-and-upgrades/installation-guide/deploying-liferay-commerce-to-an-existing-liferay-installation.html

**Comment by rdai10** [comment]
Hey @andrewwilkinsonLR I think it's good to use the markdown files as a reference, the site isn't meant to match markdown 100%, just fyi.
