### ISSUE TITLE
Incorrect image shown in custom product content renderer tutorial

### ISSUE THREAD

**Issue by jhanda** [liferay/liferay-learn#120]
**Describe the bug**
The image shown after step 5 in the [Implementing a Custom Product Content Renderer](https://learn.liferay.com/commerce-2.x/developer-guide/tutorials/implementing-a-custom-product-content-renderer.html) tutorial is incorrect

**To Reproduce**
1. Go to https://learn.liferay.com/commerce-2.x/developer-guide/tutorials/implementing-a-custom-product-content-renderer.html#walk-through-the-example.
2. Follow the directions up through step 5

**Expected behavior**
See an image that shows the widget configuration

**Screenshots**
https://learn.liferay.com/commerce-2.x/_images/0221.png

**Additional context**
NA

**Comment by justinchoi001** [comment]
@Alec-Shay , can you please take a look at this? Thanks.

**Comment by justinchoi001** [comment]
I have created: https://issues.liferay.com/browse/LRDOCS-7993.
