### ISSUE TITLE
Headers don't format with a solid line below them

### ISSUE THREAD

**Issue by andrewwilkinsonLR** [liferay/liferay-learn#13]
**Describe the bug**
Headers don't format with a solid line below them.

![image](https://user-images.githubusercontent.com/51930500/68906913-ba92e080-06fa-11ea-92b2-e6cdc5731ec8.png)

Github: https://github.com/jrhoun/liferay-learn/blob/master/docs/commerce/2.x/en/installation-and-upgrades/installation-guide/deploying-liferay-commerce-to-an-existing-liferay-installation.md

Site: https://s3.wasabisys.com/learn.liferay.com/commerce-2.x/html/docs/installation-and-upgrades/installation-guide/deploying-liferay-commerce-to-an-existing-liferay-installation.html

**Comment by jrhoun** [comment]
This isn't so much a bug as a design decision about how to render the markdown. For now, I will close this out, unless you believe it's critical that we have the line.

**Comment by andrewwilkinsonLR** [comment]
That's fine to close it. Not a big deal. I might like the line.
