### ISSUE TITLE
Two highest level nav links (Getting Started and Installation and Upgrades) direct to the same page (Quick Start Guide)

### ISSUE THREAD

**Issue by andrewwilkinsonLR** [liferay/liferay-learn#14]
**Describe the bug**
Two highest level nav links (Getting Started and Installation and Upgrades) direct to the same page (Quick Start Guide). Not sure, maybe that is the intended behavior?

![image](https://user-images.githubusercontent.com/51930500/68907496-d8614500-06fc-11ea-9716-359f80f82d20.png)

Site (main page): https://s3.wasabisys.com/learn.liferay.com/commerce-2.x/html/docs/README.html

Site (quick start guide): https://s3.wasabisys.com/learn.liferay.com/commerce-2.x/html/docs/installation-and-upgrades/quick-start-guide/quick-start-guide.html

**Comment by Alec-Shay** [comment]
This should be fixed when one of my last couple of PRs is merged in. Basically the Getting Started section doesn't have anything unique in it, so it will be removed.

**Comment by andrewwilkinsonLR** [comment]
Okay. I'll leave this open for now. Feel free to close it after you confirm it's removed later.

**Comment by jrhoun** [comment]
This is fixed. Thanks @andrewwilkinsonLR and @Alec-Shay
