### ISSUE TITLE
Self-Healing article: Values in the left column are wrapped

### ISSUE THREAD

**Issue by justinchoi001** [liferay/liferay-learn#17]
In a 2 column table, the left column contains values that exceed 10 characters are wrapped. See screenshot.
![self-healing](https://user-images.githubusercontent.com/1261044/68967674-9a642f80-0795-11ea-8c10-d9caa87ee36b.png)

**Comment by rdai10** [comment]
Hey @justinchoi001 can you provide a link to the site?

**Comment by justinchoi001** [comment]
https://s3.wasabisys.com/learn.liferay.com/dxp-cloud-latest/html/docs/troubleshooting/self-healing.html

**Comment by justinchoi001** [comment]
And also https://s3.wasabisys.com/learn.liferay.com/dxp-cloud-latest/html/getting-started/configuring-your-github-repository.html

**Comment by rdai10** [comment]
The text on the table should be wrapped so it's not overflowing. But it can be wrapped better.
