### ISSUE TITLE
Auto-scaling image displays no instances in progress bar

### ISSUE THREAD

**Issue by anthony-chu** [liferay/liferay-learn#18]
**Describe the bug**
The auto-scaling image does not display instances correctly

**To Reproduce**
1. Go to /dxp-cloud-latest/html/docs/README.html
1. View "High Availability, Scalability, and Performance" section
1. View screenshot for "Auto-scaling"

**Expected behavior**
The first bar should be a deep shade of blue to indicate one instance is available

**Actual behavior**
All bars are grey, which indicate there are no instances available, even though the text within the image indicates 1 instance in use

**Screenshots**
![image](https://user-images.githubusercontent.com/8292593/68967820-f333c800-0795-11ea-8cab-bcb04d3b2cd5.png)

**Comment by justinchoi001** [comment]
@jrhoun  and @anthony-chu , let's coordinate with the DXP Cloud team to generate a new screenshot. We were using the preexisting one from before.

**Comment by justinchoi001** [comment]
See https://github.com/jrhoun/liferay-learn/pull/50

**Comment by justinchoi001** [comment]
Please close this ticket
