### ISSUE TITLE
Missing URL in Implementing a New Tax Engine

### ISSUE THREAD

**Issue by jpince** [liferay/liferay-learn#22]
*Steps to reproduce:*
1. https://s3.wasabisys.com/learn.liferay.com/commerce-2.x/html/developer-guide/tutorial/implementing-a-new-tax-engine.html
1. Click on "Acme Commerce Tax Engine"

Actual: opens a new tab with the same page https://s3.wasabisys.com/learn.liferay.com/commerce-2.x/html/developer-guide/tutorial/implementing-a-new-tax-engine.html
Expected: info about the tax engine? link to commerce code?

*Info:*
This line in https://github.com/liferay/liferay-learn/blob/master/docs/commerce/2.x/en/developer-guide/tutorial/implementing-a-new-tax-engine.md is missing the URL, so I guess the page just redirects to itself.
```
1. Download and unzip [Acme Commerce Tax Engine]().
```

**Comment by jrhoun** [comment]
Thanks @jpince. This issue will be resolved by https://github.com/liferay/liferay-learn/issues/23 - I made a bigger more generic task for that - we will need to work w/ Brian on the site building side to fix this.
