### ISSUE TITLE
Commerce Dev Tutorial Sample zip links don't work

### ISSUE THREAD

**Issue by jrhoun** [liferay/liferay-learn#23]
The zips have not been created or uploaded yet as part of the site build process. This will result in a bad experience for anyone looking at the commerce dev tutorials (or any future dev tutorials that rely on downloadable samples).

**Comment by rdai10** [comment]
https://github.com/liferay/liferay-learn/commit/42dfdb5f6c0176693b86bf49ec27e8516df5593c
