### ISSUE TITLE
Development Requirements page missing link

### ISSUE THREAD

**Issue by anthony-chu** [liferay/liferay-learn#24]
**Describe the bug**
On the "Development Requirements" page, the text "Configuring Services for the First Time" is not hyperlinked to any page

**To Reproduce**
1. Navigate to /dxp-cloud-latest/html/getting-started/development-requirements.html
1. Scroll to "Additional Information"
1. View text "Configuring Services for the First Time"

**Expected behavior**
The text is hyperlinked to a page

**Actual result**
No page is linked

**Screenshots**
![image](https://user-images.githubusercontent.com/8292593/68971170-ce435300-079d-11ea-90e1-62a3945e49ec.png)

**Comment by jrhoun** [comment]
This will be fixed on next push. Thanks @anthony-chu
