### ISSUE TITLE
Nothing displayed when clicking on main content headings - Incorrect URL

### ISSUE THREAD

**Issue by jpince** [liferay/liferay-learn#25]
**To Reproduce**
1. Navigate to Commerce https://s3.wasabisys.com/learn.liferay.com/commerce-2.x/html/README.html
2. Click on 'Installation and Upgrades'

**Expected behavior**
URL should end with: installation-and-upgrades/README.html
I should be able to see links to all of the sub-topics
![image](https://user-images.githubusercontent.com/14880618/68971358-32661700-079e-11ea-8608-a9cf5f72fd3c.png)

**Actual result**
URL ends with: installation_and_upgrades.html
No links
![image](https://user-images.githubusercontent.com/14880618/68971336-21b5a100-079e-11ea-95e9-bdb2ef613b52.png)

This path works: Click on any subheading, then click "Go Back"

**Comment by rdai10** [comment]
relates to https://github.com/liferay/liferay-learn/issues/19

**Comment by jrhoun** [comment]
Fixed here: https://github.com/liferay/liferay-learn/commit/d0415c50053336b26a4635d779e6cc7f3ac38ed4
