### ISSUE TITLE
Development Requirements - JDK requirement is not clear

### ISSUE THREAD

**Issue by anthony-chu** [liferay/liferay-learn#26]
**Describe the bug**
The customer is instructed to use JDK1.8 or later for running Liferay DXP locally; however, we only specifically support JDK1.8 or JDK11 for run-time. Using "JDK1.8 or later" may mislead developers into thinking we also support JDK9 or JDK10.

**To Reproduce**
1. Navigate to /dxp-cloud-latest/html/getting-started/development-requirements.html
1. View JDK requirement in development requirements list

**Expected behavior**
The JDK requirement is restricted to the JDKs we support

**Actual behavior**
The JDK requirement only provides a starting point (JDK1.8) but does not include supported JDKs (JDK11) or exclude unsupported JDKs (JDK9, JDK10).

**Comment by justinchoi001** [comment]
Yes, change it.

**Comment by justinchoi001** [comment]
Assigned to @justinchoi001

**Comment by jrhoun** [comment]
@anthony-chu - @justinchoi001 updated the text of the material - please reopen this if you feel it's not satisfactory.
