### ISSUE TITLE
"Accelerated Development with Built-in CICD" anchor on article does not go to location

### ISSUE THREAD

**Issue by justinchoi001** [liferay/liferay-learn#27]
**Describe the bug**

**To Reproduce**
1. Go to 'https://s3.wasabisys.com/learn.liferay.com/dxp-cloud-latest/html/README.html'
2. Click on 'Accelerated Development with built-in cicd'

** Expected behavior**
It should go down the section in the article.

**Comment by rdai10** [comment]
This anchor: 
![image](https://user-images.githubusercontent.com/6843719/68971774-23339900-079f-11ea-9401-1c130d3d6362.png)

The anchor links on the right hand side of page works properly.

**Comment by justinchoi001** [comment]
Fixed by previous PR
