### ISSUE TITLE
Broken link in "Configuring the Liferay DXP Service" page

### ISSUE THREAD

**Issue by anthony-chu** [liferay/liferay-learn#28]
**Describe the bug**
In the "Configuring the Liferay DXP Service" page, the link to "the environment variables reference" page is broken and does not load properly

**To Reproduce**
1. Navigate to /dxp-cloud-latest/html/using-the-liferay-dxp-service/configuring-the-liferay-dxp-service.html
1. Scroll down to "Portal Properties"
1. In the note, click "the environment variables reference"

**Expected behavior**
User is redirected to a page listing the environment variables

**Actual result**
User is shown "AccessDenied" page

**Screenshots**
![20191115120049_ShareX_Capture](https://user-images.githubusercontent.com/8292593/68971993-9f2de100-079f-11ea-82ad-7921fc254b4d.gif)

**Comment by justinchoi001** [comment]
Assigned to @justinchoi001

**Comment by justinchoi001** [comment]
@anthony-chu , @jrhoun , No Longer Reproducible on the live site. I was able to navigate from Configuring the Liferay Service to Introduction to the Liferay Service's internal anchor.

https://learn.liferay.com/dxp-cloud-latest/using-the-liferay-dxp-service/configuring-the-liferay-dxp-service.html

**Comment by jrhoun** [comment]
Thanks @justinchoi001
