### ISSUE TITLE
Broken link; XML error when clicking on Dynatrace Integration

### ISSUE THREAD

**Issue by nikki-pru** [liferay/liferay-learn#29]
**Describe the bug**
Clicking on the Dynatrace Integration link yields XML errors; Link is broken. Also redirect link does not point to Dynatrace

**To Reproduce**
1. Go to 'https://s3.wasabisys.com/learn.liferay.com/dxp-cloud-latest/html/README.html#insightful-monitoring'
2. Click on 'Dynatrace Integration'

**Expected behavior**
User should be redirected to the Dynatrace link

**Additional context**
XML error
`This XML file does not appear to have any style information associated with it. The document tree is shown below.`
`<Error>`
`<Code>AccessDenied</Code>`
`<Message>Access Denied</Message>`
`<RequestId>2038C93E1AB3F248</RequestId>`
`<HostId>
gDDaNyg8E9xowAco8Y+95qLbIBqla27XpDqNhB3B3nxiX/ZC6jYjn5F7kLPfUv4Ac2/2QE53HjaS`
`</HostId>`
`</Error>`

**Comment by justinchoi001** [comment]
Assigned to @justinchoi001 .

@jrhoun ,  Please close as NLR. The links work on the live site. Same reason as bug #28 .

CC @nikki-pru .

**Comment by jrhoun** [comment]
Yup it's fixed now.
