### ISSUE TITLE
"Search Service" link in "Migrating from an On-Premises DXP Installation" page points to wrong page

### ISSUE THREAD

**Issue by anthony-chu** [liferay/liferay-learn#30]
**Describe the bug**
In "Migrating from an On-Premises DXP Installation", the link to "Search Service" redirects to a /dxp-cloud-latest/html/platform-services/continuous-integration.html, a page on CI, not on the Search service.

**To Reproduce**
1. Navigate to /dxp-cloud-latest/html/using-the-liferay-dxp-service/migrating-from-an-on-premises-dxp-installation.html
1. Scroll down to "Add Service Configurations"
1. Click the "Search Service" link in the last paragraph of the section

**Expected behavior**
User is redirected to a page on the Search service

**Actual behavior**
User is redirected to a page on CI

**Comment by justinchoi001** [comment]
Reproduced.

**Comment by justinchoi001** [comment]
Fixed by https://github.com/jrhoun/liferay-learn/pull/29. Please close
