### ISSUE TITLE
Dropdown is defaulted to Commerce in DXP Cloud Site

### ISSUE THREAD

**Issue by nikki-pru** [liferay/liferay-learn#31]
**Describe the bug**
Navigating to the DXP Cloud site via URL shows Commerce on the left document selector dropdown

**To Reproduce**
1. Go to 'https://s3.wasabisys.com/learn.liferay.com/dxp-cloud-latest/html/README.html'

**Expected behavior**
The Document Selector should show DXP Cloud since that's the page navigated to. Leaving the "Commerce" option as default messes with Context since it also looks like the header for the left navigation panel

**Screenshots**
![commerceCloud](https://user-images.githubusercontent.com/8631690/68972527-e9639200-07a0-11ea-9388-04d1d58ec081.PNG)

**Comment by rdai10** [comment]
This issue will be fixed once the breadcrumb is working again.
