### ISSUE TITLE
Can't Go Back

### ISSUE THREAD

**Issue by nikki-pru** [liferay/liferay-learn#35]
**Describe the bug**
There's no going back. Go Back link does not work

**To Reproduce**
1. Go to 'https://s3.wasabisys.com/learn.liferay.com/dxp-cloud-latest/html/README.html'
2. Click on Troubleshooting on the left panel
3. Click on Go Back

**Expected behavior**
A user should be able to go back to where he navigated from

**Comment by justinchoi001** [comment]
This was intermittent for me. I had to click Go Back several times and it worked.

**Comment by justinchoi001** [comment]
@jrhoun , please closed as NLR; works on the live site.

**Comment by jrhoun** [comment]
Behavior is still a little wonky in some areas but going to close this general ticket in favor of more specific tickets that we'll open in the near future.
