### ISSUE TITLE
Initially expected the left carrot to collapse, but it was actually to go back

### ISSUE THREAD

**Issue by reizero00** [liferay/liferay-learn#36]
The experience behind using < in the left menu was a little confusing at first since I initially expected this to just collapse the menu. 

![Peek 2019-11-14 15-58](https://user-images.githubusercontent.com/1261063/68974280-2e89c300-07a5-11ea-93bf-842ec6d1b18b.gif)

**Comment by justinchoi001** [comment]
UX issue

**Comment by jrhoun** [comment]
Closing this because the left carrot or lobster claw as some may call it has been updated to explicitly state its purpose.

**Comment by rdai10** [comment]
🦞

**Comment by reizero00** [comment]
This is much nicer!

![Screenshot at 2019-11-20 12-12-18](https://user-images.githubusercontent.com/1261063/69274337-03c9b100-0b8f-11ea-957e-2f9c21570035.png)
