### ISSUE TITLE
All 8 of the links in this table are broken. (Page = Using the Minium Accelerator to Jump-Start Your B2B Store | Section of page = Other Configurations)

### ISSUE THREAD

**Issue by andrewwilkinsonLR** [liferay/liferay-learn#42]
**Describe the bug**
All 8 of the links in this table are broken. (Page = Using the Minium Accelerator to Jump-Start Your B2B Store | Section of page = Other Configurations)

![image](https://user-images.githubusercontent.com/51930500/68979278-f3da5780-07b1-11ea-99ac-d310d285f2d9.png)

Clicking each link takes me to this page (with various RequestId and HostId):
![image](https://user-images.githubusercontent.com/51930500/68979347-1cfae800-07b2-11ea-81e5-fd969fa293e4.png)

Github: https://github.com/jrhoun/liferay-learn/blob/master/docs/commerce/2.x/en/user-guide/getting-started/using-the-minium-accelerator-to-jump-start-your-b2b-store.md

Site: https://s3.wasabisys.com/learn.liferay.com/commerce-2.x/html/user-guide/getting-started/using-the-minium-accelerator-to-jump-start-your-b2b-store.html

**Comment by Alec-Shay** [comment]
@rdai10 This seems to be an issue with Sphinx not parsing the links (the links still point to `.md` instead of the actual html pages). Is this something that would be easy to fix?

**Comment by rdai10** [comment]
@Alec-Shay Can you try removing the `.md` extension?

**Comment by Alec-Shay** [comment]
@rdai10 Removing `.md` from the links leads to a still broken page, just without the md at the end. It works if `.html` is added to the end, though I'm not sure if this is something that is acceptable to essentially hard-code the path to the page. Too fragile maybe, if it breaks and Sphinx is no longer aware of it?

**Comment by rdai10** [comment]
Hmm @Alec-Shay maybe https://github.com/liferay/liferay-learn/issues/34 will help?

**Comment by Alec-Shay** [comment]
@rdai10 I'm not sure how #34 would work in practice, so I can't really say. That said, I know we do need to still look at the `.rst` files; I've just been taking a lazy approach to fixing an issue with them here and there, but I'm sure there is more to still be addressed. Especially since we are still going to probably need to do some reorganizing with user guide docs that will mean needing to add another level of nesting in the directory.

**Comment by jrhoun** [comment]
This is fixed now. Thank you!
