### ISSUE TITLE
Left nav is very very flat (2 levels only?). Not necessarily a bad thing; might be on purpose...

### ISSUE THREAD

**Issue by andrewwilkinsonLR** [liferay/liferay-learn#43]
**Describe the bug**
Left nav is very very flat (2 levels only?). Not necessarily a bad thing; might be on purpose...but it also means NO grouping of articles into categories. And it means a very long scroll bar (might be intimidating?).

For example, in the user guide, it appears that (maybe) all of the articles in the user guide are displayed and clickable on the very, very long (scrollable) left nav.

![image](https://user-images.githubusercontent.com/51930500/68980129-6cdaae80-07b4-11ea-8e51-621d3f66a972.png)

Site: https://s3.wasabisys.com/learn.liferay.com/commerce-2.x/html/user-guide/getting-started/liferay-commerce-configuration-overview.html

**Comment by jrhoun** [comment]
This is fixed on prod.
