### ISSUE TITLE
Additional Information section at bottom of page doesn't link the user to additional article

### ISSUE THREAD

**Issue by rdai10** [liferay/liferay-learn#46]
**Describe the bug**
When a user is looking at additional information, the titles listed there should take the user to some kind of content.

**To Reproduce**
1. Go to https://s3.wasabisys.com/learn.liferay.com/commerce-2.x/user-guide/sales/order-workflows.html
2. Scroll to the bottom for "Additional Information"

**Expected behavior**
All the information listed to be links that can take the user somewhere. 

**Screenshots**
![image](https://user-images.githubusercontent.com/6843719/68981520-8a117c00-07b8-11ea-9375-8a502b56afcd.png)

**Comment by justinchoi001** [comment]
Assigned to @justinchoi001

**Comment by justinchoi001** [comment]
I am fixing the other articles in the Orders section:
1. Orders Menu
2. Order management Statuses
3. Order Life Cycle
4. Order information

**Comment by justinchoi001** [comment]
Fixed by jrhoun#29. Please close.
