### ISSUE TITLE
Broken link on "Web Application Firewall" page

### ISSUE THREAD

**Issue by anthony-chu** [liferay/liferay-learn#51]
**Describe the bug**
The "CDN" link, which should point to the "Load Balancer" page, is broken and redirects to an "AccessDenied" page

**To Reproduce**
1. Navigate to /dxp-cloud-latest/html/infrastructure-and-operations/security/web-application-firewall.html
1. Navigate to "CDN Offload" section
1. Click the link "CDN"

**Expected behavior**
User is redirected to a page on the CDN

**Actual behavior**
User is brought to an Access Denied page

**Comment by Alec-Shay** [comment]
This is related to an issue with any links to sections of other articles (so there is #something at the end after the `.md` in the link) do not properly redirect to the page. For reference: https://github.com/liferay/liferay-learn/issues/34

**Comment by jrhoun** [comment]
Fixed this. Should be fixed on next push. Thanks @anthony-chu
