### ISSUE TITLE
Article Title in L nav doesn't match article title in Github TOC (might be okay?)

### ISSUE THREAD

**Issue by andrewwilkinsonLR** [liferay/liferay-learn#52]
**Describe the bug**
Article Title in L nav doesn't match article title in Github TOC (might be okay?)

While the article title _on the article pages themselves_ are the same on both Github and the Site, on Github's TOC the article has a shortened/different title. On the Site L nav, the full title of the article displays.

L Nav with different title than Github TOC:
![image](https://user-images.githubusercontent.com/51930500/68984352-6c4a1400-07c4-11ea-8bd0-45c67f85d58b.png)

Article pages having same title:
![image](https://user-images.githubusercontent.com/51930500/68984420-d82c7c80-07c4-11ea-89f3-2504a5f59dd9.png)

This (no shortened/different titles) might be okay/the intended behavior. Just raising it as an issue in case it's not intentional or if there's something to check or fix.

Github: https://github.com/jrhoun/liferay-learn/tree/master/docs/commerce/2.x/en/user-guide

Site: https://s3.wasabisys.com/learn.liferay.com/commerce-2.x/user-guide/marketing/automating-store-emails-by-using-notification-templates.html

**Comment by jrhoun** [comment]
Fixed the inconsistency.
