### ISSUE TITLE
Two links (Money Order and PayPal) mistakenly direct to the wrong article (Mercanet) on the "Managing Payment Methods" page.

### ISSUE THREAD

**Issue by andrewwilkinsonLR** [liferay/liferay-learn#55]
**Describe the bug**
Two links (Money Order and PayPal) mistakenly direct to the wrong article (Mercanet) on the "Managing Payment Methods" page.

The links are in the "Additional Information" at the very bottom of the page.

![image](https://user-images.githubusercontent.com/51930500/68985772-ec28ac00-07cd-11ea-8196-7b03d3031b54.png)

There are four links in the Additional Information, but three of them go to Mercanet (and only one of them should - the Mercanet article link); the "Authorize.net" link is correct.

Github: https://github.com/jrhoun/liferay-learn/blob/master/docs/commerce/2.x/en/user-guide/getting-started/managing-payment-methods.md

Site: https://s3.wasabisys.com/learn.liferay.com/commerce-2.x/user-guide/getting-started/managing-payment-methods.html

**Comment by justinchoi001** [comment]
Assigned to @justinchoi001 . Fix in progress.

**Comment by justinchoi001** [comment]
Fixed by https://github.com/jrhoun/liferay-learn/pull/29. Please close.
