### ISSUE TITLE
Link to "Selling Grouped Products" section has a typo (so it doesn't direct/go to the section header).

### ISSUE THREAD

**Issue by andrewwilkinsonLR** [liferay/liferay-learn#57]
**Describe the bug**
Link to "Selling Grouped Products" section has a typo (so it doesn't direct/go to the section header).

The markdown (see Github) has the following text: "* #setting-grouped-products".

The header is "Selling...", but the link says "#setting".

Solution: Change the markdown file so that the line reads as follows: "* #selling-grouped-products".

Clicking this link ("Selling Grouped Products")...
![image](https://user-images.githubusercontent.com/51930500/69022808-5af23a80-0971-11ea-91b9-3bbb32e7d404.png)

...takes me to the top of the article page (or stays at the top of the page?)...
![image](https://user-images.githubusercontent.com/51930500/69023274-123b8100-0973-11ea-968d-9124dfed4145.png)

...rather than to the correct section (shown below with correct/modified URL).
![image](https://user-images.githubusercontent.com/51930500/69022932-c936fd00-0971-11ea-80eb-9b1a7d39fb1a.png)

Github: https://github.com/jrhoun/liferay-learn/blob/master/docs/commerce/2.x/en/user-guide/catalog/creating-a-grouped-product.md

Site: https://s3.wasabisys.com/learn.liferay.com/commerce-2.x/user-guide/catalog/creating-a-grouped-product.html

**Comment by justinchoi001** [comment]
documentation bug

**Comment by justinchoi001** [comment]
Fixed by https://github.com/jrhoun/liferay-learn/pull/29. Please close
