### ISSUE TITLE
Link to "Creating Categories" section has a typo (so it doesn't direct/go to the section header). (Same as issue #57 for a different page & link.)

### ISSUE THREAD

**Issue by andrewwilkinsonLR** [liferay/liferay-learn#58]
**Describe the bug**
Link to "Creating Categories" section has a typo (so it doesn't direct/go to the section header). (Same as issue #57 for a different page & link.)

The markdown (see Github) has the following text: "* #creating-a-category" in the Roadmap, link for "Create a Category".

The ##header (header2) is "Creating Categories" (plural), but the link says "#creating-a-category" (singular).

Solution: Change the markdown file so that the line reads as follows: "* #creating-categories".

![image](https://user-images.githubusercontent.com/51930500/69025268-2daa8a00-097b-11ea-9a36-d3ac99ee5367.png)

Github: https://github.com/jrhoun/liferay-learn/blob/master/docs/commerce/2.x/en/user-guide/catalog/creating-a-new-product-category.md

Site: https://s3.wasabisys.com/learn.liferay.com/commerce-2.x/user-guide/catalog/creating-a-new-product-category.html

**Comment by jrhoun** [comment]
Fixed.
