### ISSUE TITLE
Broken image-link on "Product Categories" article (the image-link text, and not the image, is displayed in the article).

### ISSUE THREAD

**Issue by andrewwilkinsonLR** [liferay/liferay-learn#61]
**Describe the bug**
Broken image-link on "Product Categories" article (the image-link text, and not the image, is displayed in the article).

![image](https://user-images.githubusercontent.com/51930500/69063571-9886b000-09d1-11ea-92f7-ce4e1037af7e.png)

Solution: The markdown might just be missing an "[" after the initial "!".

Github: https://github.com/jrhoun/liferay-learn/blob/master/docs/commerce/2.x/en/user-guide/catalog/organizing-your-catalog-with-product-categories.md

Site: https://s3.wasabisys.com/learn.liferay.com/commerce-2.x/user-guide/catalog/organizing-your-catalog-with-product-categories.html

**Comment by jrhoun** [comment]
Fixed. Will be in the next push to the site.
