### ISSUE TITLE
Some of the "Managing Inventory" articles in L Nav appear to be out of order (and there is an article in the L Nav that doesn't appear in the Github outline).

### ISSUE THREAD

**Issue by andrewwilkinsonLR** [liferay/liferay-learn#63]
**Describe the bug**
Some of the "Managing Inventory" articles in L Nav appear to be out of order (and there is an article in the L Nav that doesn't appear in the Github outline).

image
![image](https://user-images.githubusercontent.com/51930500/69069343-2a46eb00-09db-11ea-81bc-3790544df129.png)

On the Github outline, the order is:
**Managing Inventory**
 * Introduction to Managing Inventory
 * Adding a New Warehouse
 * Setting Inventory by Warehouse
 * Low Inventory Activity
 * Availability Estimates
 * Product Inventory Configuration Reference
 * Managing Product Publication

On the site L Nav, the order is:
**Managing Inventory**
 * _Managing Product Publication_ (out of order)
 * Introduction to Managing Inventory
 * _Warehouse Reference Guide_ (not in Github outline)
 * Adding a New Warehouse
 * Setting Inventory by Warehouse
 * Low Inventory Activity
 * Availability Estimates
 * Product Inventory Configuration Reference

Github Outline: https://github.com/jrhoun/liferay-learn/tree/master/docs/commerce/2.x/en/user-guide

Site: https://s3.wasabisys.com/learn.liferay.com/commerce-2.x/user-guide/catalog/managing-product-publication.html

**Comment by jrhoun** [comment]
We probably need to fix the ordering in the RST file. @Alec-Shay

**Comment by justinchoi001** [comment]
1. I can still see _Managing Product Publication_ list before _Introduction to Managing Inventory._
2. The Warehouse Reference article probably was not listed on the first iterations of the outline.

**Comment by jrhoun** [comment]
Should be fixed on next push to the site.
