### ISSUE TITLE
An article in the "Additional Information" section says "(TODO)". But I think the article exists. Replace " Shipping - Creating a New Shipment (TODO)" with this text "Creating a Shipment" and a link to the article.

### ISSUE THREAD

**Issue by andrewwilkinsonLR** [liferay/liferay-learn#64]
**Describe the bug**
An article in the "Additional Information" section says "(TODO)". But I think the article exists. Replace " Shipping - Creating a New Shipment (TODO)" with this text "Creating a Shipment" and a link to the article.

![image](https://user-images.githubusercontent.com/51930500/69070477-13a19380-09dd-11ea-9c7c-db6c12b50417.png)

I think this is the "Creating a Shipment" article to link to: 
  * Site: https://s3.wasabisys.com/learn.liferay.com/commerce-2.x/user-guide/sales/creating-a-shipment.html
  * Github: https://github.com/jrhoun/liferay-learn/blob/master/docs/commerce/2.x/en/user-guide/sales/creating-a-shipment.md

Github: https://github.com/jrhoun/liferay-learn/blob/master/docs/commerce/2.x/en/user-guide/catalog/introduction-to-managing-inventory.md

Site: https://s3.wasabisys.com/learn.liferay.com/commerce-2.x/user-guide/catalog/introduction-to-managing-inventory.html

**Comment by justinchoi001** [comment]
Assigned to @justinchoi001. Fix is on the way.

**Comment by justinchoi001** [comment]
Fixed by jrhoun#29. Please close.
