### ISSUE TITLE
Typo: On the "Creating a Price List" article, in the "Additional Information" section, there are text links with different titles but the same URL destination: "Adding Products to a Price List" & "Adding Tiered Pricing".

### ISSUE THREAD

**Issue by andrewwilkinsonLR** [liferay/liferay-learn#66]
**Describe the bug**
Typo: On the "Creating a Price List" article, in the "Additional Information" section, there are text links with different titles but the same URL destination: "Adding Products to a Price List" & "Adding Tiered Pricing".

This appears to be a mistake. I think this is the correct URL for the latter link: https://learn.liferay.com/commerce-2.x/user-guide/catalog/adding-tiered-pricing.html

Solution: Change the last linke in the "d" markdown file:

From this: (../catalog/adding-products-to-a-price-list.md)

To this: (../catalog/adding-tiered-pricing.md)

~This is not necessarily a mistake; maybe it is intentional in order to help people find the article from multiple key words "price list" and "tiered pricing". But it's not typical to have two links to the same article, so flagging it here.~

Here are the two text links with different titles but the same URL destination (on the "Creating a Price List" article, in the "Additional Information" section):
![image](https://user-images.githubusercontent.com/51930500/69081213-6174c680-09f2-11ea-9651-143926be029b.png)

Each of the two text links take me to this article, "Adding Products to a Price List":
![image](https://user-images.githubusercontent.com/51930500/69081573-1ad39c00-09f3-11ea-9852-2eb7eb5b71f0.png)

Github (Creating a Price List): https://github.com/jrhoun/liferay-learn/blob/master/docs/commerce/2.x/en/user-guide/catalog/creating-a-price-list.md

Site (Creating a Price List): https://learn.liferay.com/commerce-2.x/user-guide/catalog/creating-a-price-list.html

(Goes to) Site (Adding Products to a Price List): https://learn.liferay.com/commerce-2.x/user-guide/catalog/adding-products-to-a-price-list.html

(EDIT: These two links are also in the Github outline and in the learn.liferay.com L Nav.
![image](https://user-images.githubusercontent.com/51930500/69082556-2cb63e80-09f5-11ea-99e1-17fc2b09436b.png)

But in those locations, it appears that the links are correct.)

**Comment by justinchoi001** [comment]
assigned to @justinchoi001

**Comment by justinchoi001** [comment]
Fixed in: https://github.com/jrhoun/liferay-learn/pull/47
