### ISSUE TITLE
The "Automating Store Emails by Using Notification Templates" article appears twice in the L nav.

### ISSUE THREAD

**Issue by andrewwilkinsonLR** [liferay/liferay-learn#67]
**Describe the bug**
The "Automating Store Emails by Using Notification Templates" article appears twice in the L nav.

![image](https://user-images.githubusercontent.com/51930500/69084630-83257c00-09f9-11ea-8310-d9c5ec15ddca.png)

![image](https://user-images.githubusercontent.com/51930500/69084483-3641a580-09f9-11ea-94ee-4bf9a5c5f526.png)

Github: https://github.com/jrhoun/liferay-learn/blob/master/docs/commerce/2.x/en/user-guide/marketing/automating-store-emails-by-using-notification-templates.md

Site: https://learn.liferay.com/commerce-2.x/user-guide/marketing/automating-store-emails-by-using-notification-templates.html

**Comment by jrhoun** [comment]
Fixed this. Good find @andrewwilkinsonLR . Should be fixed on next push.
