### ISSUE TITLE
404 page is not rendering correctly

### ISSUE THREAD

**Issue by jrhoun** [liferay/liferay-learn#68]
**Describe the bug**
When visiting an invalid URL for learn.liferay.com - the 404 page does appear, but is rendered incorrectly.

**To Reproduce**
1. Go to learn.liferay.com/commerce-2.x/html/user-guide/operations/setting-tax-rate-by-fixed-rate.html#additional-information
2. See screenshot below.

**Screenshots**
![image](https://user-images.githubusercontent.com/597214/69085305-a866ba00-09fa-11ea-9095-989104a01d4c.png)

**Comment by rdai10** [comment]
Appears to be fixed on UAT:
![image](https://user-images.githubusercontent.com/6843719/73219128-3f917180-4110-11ea-90a5-5352795a0280.png)

**Comment by rdai10** [comment]
closed by 7250cf72947c2e0f7ee46941be49307cdae1158b
