### ISSUE TITLE
Broken image link (possibly a typo): A markdown image displays as code instead (in the "Adding Discounts by Product" article, in the "Adding Rules to a Discount" section).

### ISSUE THREAD

**Issue by andrewwilkinsonLR** [liferay/liferay-learn#69]
**Describe the bug**
Broken image link (possibly a typo): A markdown image displays as code instead (in the "Adding Discounts by Product" article, in the "Adding Rules to a Discount" section).

![image](https://user-images.githubusercontent.com/51930500/69101756-48314180-0a15-11ea-9061-9403b60553f1.png)

The markdown text for the image link (that displays as code) is: "!" "[Discount rule types dropdown]" "(./adding-discounts-by-product/images/03.png)"

(I think the image that was intended to be displayed looks something like this, as copied/pasted from the "[Adding Discounts to the Subtotal](https://learn.liferay.com/commerce-2.x/user-guide/marketing/adding-discounts-to-the-subtotal.html)" article:
![image](https://user-images.githubusercontent.com/51930500/69102833-77957d80-0a18-11ea-95bf-84c855f2b700.png))

Github: https://github.com/jrhoun/liferay-learn/blob/master/docs/commerce/2.x/en/user-guide/marketing/adding-discounts-by-product.md

Site: https://learn.liferay.com/commerce-2.x/user-guide/marketing/adding-discounts-by-product.html

**Comment by justinchoi001** [comment]
See https://github.com/jrhoun/liferay-learn/pull/31

**Comment by justinchoi001** [comment]
Documentation bug

**Comment by jrhoun** [comment]
Fixed.
