### ISSUE TITLE
There is no "Additional Information" section at the bottom of the "Liferay Commerce Widget Reference List" article.

### ISSUE THREAD

**Issue by andrewwilkinsonLR** [liferay/liferay-learn#70]
**Describe the bug**
There is no "Additional Information" section at the bottom of the "Liferay Commerce Widget Reference List" article.

This is not necessarily a problem. But I think that most, if not all, articles on the Site have this feature.

![image](https://user-images.githubusercontent.com/51930500/69103559-8aa94d00-0a1a-11ea-8ff7-b32b67ef6ca5.png)

Solution: Add the following two articles as "Additional Information":
 * [Creating Your Storefront](https://learn.liferay.com/commerce-2.x/user-guide/content/creating-your-storefront.html)
 * [Creating Pages](https://help.liferay.com/hc/en-us/articles/360018171291-Creating-Pages)

Proposed Solution (visual):
![image](https://user-images.githubusercontent.com/51930500/69103768-263abd80-0a1b-11ea-9fad-c0c279650022.png)

Github: https://github.com/jrhoun/liferay-learn/blob/master/docs/commerce/2.x/en/user-guide/content/widget-reference.md

Site: https://learn.liferay.com/commerce-2.x/user-guide/content/widget-reference.html

**Comment by justinchoi001** [comment]
See https://github.com/jrhoun/liferay-learn/pull/46
