### ISSUE TITLE
Another article ("Creating a Catalog Page") in the L Nav that doesn't appear in the Github outline.

### ISSUE THREAD

**Issue by andrewwilkinsonLR** [liferay/liferay-learn#72]
**Describe the bug**
Another article ("Creating a Catalog Page") in the L Nav that doesn't appear in the Github outline.

![image](https://user-images.githubusercontent.com/51930500/69105679-dfe85d00-0a20-11ea-97ef-61d63bb58ef2.png)

Site: https://learn.liferay.com/commerce-2.x/user-guide/content/creating-a-catalog-page.html

Github: (where is it?)

For similar, see Issue #63.
For related, see Issue #71.

**Comment by jrhoun** [comment]
Fixed here: https://github.com/liferay/liferay-learn/commit/a9d94a3dfac67efc4cdd2893c95b44b3cafe777e
