### ISSUE TITLE
Searching for "DXP Cloud" or "Commerce" in the home page search bar gives seemingly alphabetically-ordered results (not by importance, how often it was searched for, etc.). And include basically duplicate pages (with different URL but same content).

### ISSUE THREAD

**Issue by andrewwilkinsonLR** [liferay/liferay-learn#79]
**Describe the bug**
Searching for "DXP Cloud" or "Commerce" in the home page search bar gives seemingly alphabetically-ordered results (not by importance, how often it was searched for, etc.). And include basically duplicate pages (with different URL but same content).

**Search for "DXP Cloud"**

The top results are (and include duplicates):
![image](https://user-images.githubusercontent.com/51930500/69201634-ca903300-0af3-11ea-8d05-697d1dfec282.png)

 * Search Result ("Build and Deploy" - the first one listed)
![image](https://user-images.githubusercontent.com/51930500/69201648-d976e580-0af3-11ea-92cd-0fb17b4ceb03.png)

 * Search Result ("Build and Deploy" - the second one listed - notice it's the same content, just a different URL AND DIFFERENT L Nav)
![image](https://user-images.githubusercontent.com/51930500/69201687-04613980-0af4-11ea-8d8d-76de96912258.png)

 * Search Result ("Configuring the Liferay DXP Service" - the third result)
https://learn.liferay.com/dxp-cloud-latest/using-the-liferay-dxp-service/configuring-the-liferay-dxp-service.html?highlight=dxp%20cloud

**Search for "Commerce"**

![image](https://user-images.githubusercontent.com/51930500/69201718-222e9e80-0af4-11ea-8254-b8b96e6299a8.png)

**Comment by rdai10** [comment]
Hey @andrewwilkinsonLR ,
The content is different. But we should probably reorder the product.
