### ISSUE TITLE
Tab doesn't format

### ISSUE THREAD

**Issue by andrewwilkinsonLR** [liferay/liferay-learn#8]
**Describe the bug**
Markdown of "    > text" doesn't format as a tab.

![image](https://user-images.githubusercontent.com/51930500/68906054-055f2900-06f8-11ea-9b32-8076a9cf8020.png)

github: https://github.com/jrhoun/liferay-learn/blob/master/docs/commerce/2.x/en/installation-and-upgrades/quick-start-guide/quick-start-guide.md

site: https://s3.wasabisys.com/learn.liferay.com/commerce-2.x/html/docs/installation-and-upgrades/quick-start-guide/quick-start-guide.html

**Comment by rdai10** [comment]
Hey @andrewwilkinsonLR I think it's good to use the markdown files as a reference, the site isn't meant to match markdown 100%, just fyi.
