### ISSUE TITLE
learn.liferay.com is not correctly rendering markdown block quote syntax: `> text`

### ISSUE THREAD

**Issue by jrhoun** [liferay/liferay-learn#81]
Example: https://learn.liferay.com/commerce-2.x/developer-guide/tutorial/adding-a-new-product-data-source-for-the-product-publisher-widget.html

![image](https://user-images.githubusercontent.com/597214/69267422-f528cd00-0b81-11ea-8573-986e39755bdb.png)

Rendered on GH: https://github.com/liferay/liferay-learn/blob/master/docs/commerce/2.x/en/developer-guide/tutorial/adding-a-new-product-data-source-for-the-product-publisher-widget.md

![image](https://user-images.githubusercontent.com/597214/69267472-0d005100-0b82-11ea-9794-c434413998f1.png)

See https://www.markdownguide.org/basic-syntax#blockquotes-1

**Comment by rdai10** [comment]
Waiting for design.

**Comment by rdai10** [comment]
https://github.com/jrhoun/liferay-learn/pull/128
