### ISSUE TITLE
Include info about upgrading FixPack when upgrading Liferay Commece

### ISSUE THREAD

**Issue by jhanda** [liferay/liferay-learn#82]
**Describe the bug**
Upgrading Liferay Commerce may also require a FixPack upgrade.  It can difficult to know exactly what steps need to be taken and in which order.  

**To Reproduce**
1. Go to https://learn.liferay.com/commerce-2.x/installation-and-upgrades/upgrades-and-updates/upgrading-from-liferay-commerce-1.1.x.html

**Expected behavior**
Since a FixPack upgrade is required to move from 1.1.x to 2.x I would expect to see some mention of when the FixPack should be applied during the upgrade steps.   

**Additional context**
In static documentation, it's impossible to keep up to date on all specific FixPack version requirements, however I think we can at least provide a step-by-step process that highlights when the new FixPack should be applied (if one is required).

**Comment by justinchoi001** [comment]
See https://github.com/jrhoun/liferay-learn/pull/53
