### ISSUE TITLE
Commerce docs - Promoting Products fixes

### ISSUE THREAD

**Issue by nkkwon** [liferay/liferay-learn#89]
Some improvements for the Commerce documentation.

[Automating Store Emails by Using Notification Templates](
https://learn.liferay.com/commerce-2.x/promoting-products/automating-store-emails-by-using-notification-templates.html)

Change "[%ORDER_CREATOR%] inserts the Order ID" in Additional Notifications to [%ORDER_ID%]

Change "Control Menu" in Note 3 to "Control Panel" to match the actual site.

**Comment by justinchoi001** [comment]
Reviewing. Thanks.
