### ISSUE TITLE
Code (bash) has a scroll bar if window is too narrow

### ISSUE THREAD

**Issue by andrewwilkinsonLR** [liferay/liferay-learn#9]
**Describe the bug**
Markdown of
    ```bash
    text
    ```
formats with a scroll bar if the browser window is too narrow.

![image](https://user-images.githubusercontent.com/51930500/68906266-92a27d80-06f8-11ea-9208-06ac5b3728e1.png)

github: https://github.com/jrhoun/liferay-learn/blob/master/docs/commerce/2.x/en/installation-and-upgrades/quick-start-guide/quick-start-guide.md

site: https://s3.wasabisys.com/learn.liferay.com/commerce-2.x/html/docs/installation-and-upgrades/quick-start-guide/quick-start-guide.html

**Comment by Alec-Shay** [comment]
Is this mostly because of the fact that the sidebars are squeezing in the content on the site? It kinda seems that way looking at the screenshots. I'll bet if the page on GitHub were squished more too it would also show a scroll bar there.

**Comment by andrewwilkinsonLR** [comment]
I think you're right. On another page with a much longer code, the github format had a scrollbar.
