### ISSUE TITLE
Commerce Docs - Upgrading from Liferay Commerce 1.1.x

### ISSUE THREAD

**Issue by Adriverforlife** [liferay/liferay-learn#90]
**Describe the bug**
Used starting version 1.1.0 to test upgrade. Patching tool instructions are inconstant with rest of documentation. Currently only mentions Windows commands where elsewhere in documentation it specifies both Windows and Linux commands.

**To Reproduce**
1. Go to 'https://learn.liferay.com/commerce-2.x/installation-and-upgrades/upgrades-and-updates/upgrading-from-liferay-commerce-1.1.x.html'
2. Scroll to "Applying the Latest Fix Patch"

**Expected behavior**
Step one would have both Windows and Linux command prompts for the terminal.

**Actual behavior**
Windows commands are listed, but not specified as Windows commands. Inconsistent
 with rest of documentation.

**Screenshots**
![Commerce2](https://user-images.githubusercontent.com/50709197/71040970-b7658880-20dc-11ea-9761-7af59443ceee.png)

**Comment by justinchoi001** [comment]
Reviewing. Thanks
