### ISSUE TITLE
Liferay Commerce Widget Reference List reference to Dashboard widget is incorrect

### ISSUE THREAD

**Issue by jhanda** [liferay/liferay-learn#99]
**Describe the bug**
The [Liferay Commerce Widget Reference List ](https://learn.liferay.com/commerce-2.x/creating-store-content/widget-reference.html)refers to a Dashboard KPI widget.  That widget is not currently available  but there is another widget called Dashboard Forecasts Chart that is available.  

**To Reproduce**
1. On an instance of Liferay DXP with Liferay Commerce deployed, go to a site and attempt to add a widget.  
2. Search for Dashboard

**Expected behavior**
A widget called Dashboard KPI should be available to add to the page.  It is not, but there is a widget called Dashboard Forecasts chart.   

**Screenshots**
![missing-dashboard-kpi-widget](https://user-images.githubusercontent.com/277412/72466098-4205da00-37a6-11ea-8ad1-e8f825967173.png)

**Additional context**

**Comment by jrhoun** [comment]
@justinchoi001 - can you take a look at this when you are able?

**Comment by justinchoi001** [comment]
Hi Jeff, 
Reviewing now.

**Comment by jrhoun** [comment]
Closing as fixed. @jhanda please let me know if the changes @justinchoi001 made are insufficient. Thank you!
